language: cpp

dist: trusty
sudo: false

matrix:
  include:
     - os: linux
       addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
       env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
     - os: linux
       addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
       env:
         - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

script:
  - eval "${MATRIX_EVAL}"
  - ./build.sh

